name: NielBot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install library
      run: pip install -r requirements.txt

    - name: Start Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: python bot.py